<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>WinRadial</RootNamespace>
    <AssemblyName>WinRadial</AssemblyName>
    <StartupObject>WinRadial.Program</StartupObject>

    <!-- Publishing -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <!-- Trim unused code for smaller binary -->
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\config.json">
      <LogicalName>WinRadial.Resources.config.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\config.schema.json">
      <LogicalName>WinRadial.Resources.config.schema.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>
